site_url: https://province9.org
site_name: Province 9 - Î¦MA (Phi Mu Alpha)
site_author: Mason Egger
repo_url: https://github.com/province9/province9.github.io
repo_name: province9/province9.github.io
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: PT Serif
  logo: assets/images/favicon.png
  custom_dir: overrides
  locale: en
  logo: assets/images/p9.png
  favicon: assets/images/p9.png
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
  palette:
    - scheme: p9_light
copyright: Copyright &copy; 2023 - Province 9

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - About: about.md
  - Chapters: chapters.md
  - Alumni: alumni.md
  - Blog:
    - blog/index.md

plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      post_url_format: "{slug}"
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 


extra:
  analytics:
    provider: google
    property: G-VBH764B9Y0
  generator: false
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@province9sinfonia605
      name: YouTube
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/province9sinfonia
      name: Instagram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/15740270162
      name: Facebook
    - icon: fontawesome/brands/discord
      link: https://discord.gg/GmPHETj7EF
      name: Discord
    - icon: fontawesome/solid/square-rss
      link: ./feed_rss_updated.xml
      name: RSS
    - icon: fontawesome/brands/github
      link: https://github.com/province9
      name: GitHub

#extra:
#  analytics:
#    provider: google
#    property: G-885F33V7K6
